name: spacey
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  dio: any
  flutter_bloc: any
  flutter_localizations:
    sdk: flutter
  freezed_annotation: any
  get_it: any
  hive: any
  hive_flutter: any
  json_annotation: any
  retrofit: any
  shared_preferences: any
  permission_handler: any
  file_manager: any
  thumbnailer: any
  video_thumbnail: any
  url_launcher: any
  open_file: any

dev_dependencies:
  build_runner: any
  flutter_lints: any
  flutter_test:
    sdk: flutter
  freezed: any
  hive_generator: any
  json_serializable: any
  path_provider: any
  retrofit_generator: any

flutter:
  uses-material-design: true
  assets:
    - assets/lang/
